add reset-system script, make sure scripts run as root first, add some confirm screens

diff --git a/bin/vpn-maint-apply-changes b/bin/vpn-maint-apply-changes
--- a/bin/vpn-maint-apply-changes
+++ b/bin/vpn-maint-apply-changes
@@ -1,5 +1,9 @@
 #!/bin/sh
 
+if ! [ "root" = "$(id -u -n)" ]; then
+    echo "ERROR: ${0} must be run as root!"; exit 1
+fi
+
 # Disable & Stop OpenVPN
 for CONFIG_NAME in $(systemctl list-units "openvpn-server@*" --no-legend | cut -d ' ' -f 1)
 do
diff --git a/bin/vpn-maint-start-node b/bin/vpn-maint-start-node
--- a/bin/vpn-maint-start-node
+++ b/bin/vpn-maint-start-node
@@ -1,3 +1,7 @@
 #!/bin/sh
 
+if ! [ "root" = "$(id -u -n)" ]; then
+    echo "ERROR: ${0} must be run as root!"; exit 1
+fi
+
 systemctl start openvpn-server@\* --all
diff --git a/bin/vpn-maint-update-controller b/bin/vpn-maint-update-controller
--- a/bin/vpn-maint-update-controller
+++ b/bin/vpn-maint-update-controller
@@ -1,5 +1,14 @@
 #!/bin/sh
 
+if ! [ "root" = "$(id -u -n)" ]; then
+    echo "ERROR: ${0} must be run as root!"; exit 1
+fi
+
+printf "Did you stop your node(s) first? [n]: "; read -r CONFIRM
+if ! [ "${CONFIRM}" = "y" ]; then
+    exit 1
+fi
+
 # Stop Web Server
 systemctl stop httpd
 systemctl stop php-fpm
diff --git a/bin/vpn-maint-update-system b/bin/vpn-maint-update-system
--- a/bin/vpn-maint-update-system
+++ b/bin/vpn-maint-update-system
@@ -1,5 +1,9 @@
 #!/bin/sh
 
+if ! [ "root" = "$(id -u -n)" ]; then
+    echo "ERROR: ${0} must be run as root!"; exit 1
+fi
+
 # Stop OpenVPN
 systemctl stop openvpn-server@\* --all
 
